version: "3.7"
services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql-8.3.0
    restart: unless-stopped               # always restart
    environment:
      MYSQL_DATABASE: 'test'              # name of database
      MYSQL_USER: 'default'               # sample is the name of user
      MYSQL_PASSWORD: 'password'          # password for sample user
      MYSQL_ROOT_PASSWORD: 'password'     # password for root user
    ports:
      - '3306:3306'                       # host port 3306 is mapper to docker port 3306
    expose:
      - '3306'
    volumes:
      - "D:/Docker volumes/MySQL:/var/lib/mysql"
volumes:
  mysql-db: